import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="nav">
          <Link href="/">
            <h2>Home</h2>
          </Link>
          <Link href="/list">
            <h2>List</h2>
          </Link>
          <Link href="/write">
            <h2>데이터 보기</h2>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
